### ISSUE TITLE
Boolean combinator missing

### ISSUE THREAD

**Issue by daddinuz** [fcracker79/pycomb#2]
Would be really cool to have a combinator for Boolean types

```python
Boolean = combinators.generic_object({}, bool)
```

**Comment by fcracker79** [comment]
Fixed in release 0.1.8.
Commit:[e35445e28047691cfd7244aedb885abe691a5b20](https://github.com/fcracker79/pycomb/commit/e35445e28047691cfd7244aedb885abe691a5b20)
